### ISSUE TITLE
Regarding newer versions of ubuntu and ros it supports

### ISSUE THREAD

**Issue by yeapzexin** [swri-robotics/Neighborhood#12]
Hi guys,
I just want to know regarding the README information, as ROS noetic and ubuntu 20.04 have been released. Does neighbourhood support them as they are newer versions instead of older versions? This is because some of my team members laptop can only support later versions of ubuntu than 18.04.

Although it might be a stupid question, just want to do know about any last hope haha

**Comment by danthony06** [comment]
We maintained this branch of Neighborhood only for the last version of the Shell Eco-marathon Autonomous Vehicle Competition. We're currently not maintaining it any more, and will not use this version in future versions of the competition. For newer versions of ROS, I suggest looking at the upstream AirSim release: https://github.com/Microsoft/AirSim.
