### ISSUE TITLE
Airsim Node consuming >7GB of RAM

### ISSUE THREAD

**Issue by ansarid** [swri-robotics/Neighborhood#4]
Running the `airsim_node` consumes >7GB of RAM while running within 10 minutes of launching the node.

**Comment by pjreed** [comment]
Thanks for pointing that out; I normally only have the node up for a few minutes at a time and stop it as soon as I'm done, so I hadn't noticed.  I pushed up a change to https://github.com/swri-robotics/AirSim that should fix that.

Note that after you pull the update, you'll need to re-run the build-neighborhood.sh script in AirSim, re-run `ue4 build` in the Neighborhood directory, and also rebuild the ROS node.  The whole process should look something like:
```bash
cd $HOME/src/AirSim
git pull
./build-neighborhood.sh
cd $HOME/src/AirSim/Unreal/Environments/Neighborhood
ue4 build
cd $HOME/src/AirSim/ros
CC=gcc-8 CXX=g++-8 catkin build
```

Then you should be able to run everything without the memory leak happening.  Let me know if that works for you and I'll update the documentation in the README.md.

**Comment by ansarid** [comment]
That seems to have solved the problem! Thank you!
