### ISSUE TITLE
Broken link at README.md

### ISSUE THREAD

**Issue by Thor-x86** [swri-robotics/Neighborhood#9]
The [settings.md](https://github.com/swri-robotics/Neighborhood/blob/master/docs/settings.md) link at README.md is broken. I also have no idea where is it going. Please fix it, thank you.

**Comment by GimpelZhang** [comment]
I think it refers to this: [AirSim Settings](https://microsoft.github.io/AirSim/settings/)

**Comment by Thor-x86** [comment]
Pull request https://github.com/swri-robotics/Neighborhood/pull/10 is merged now, I'm going to close the issue
